export const FETCH_FIGURES_REQUEST = 'FETCH_FIGURES_REQUEST';
export const FETCH_FIGURES_SUCCESS = 'FETCH_FIGURES_SUCCESS';
export const FETCH_FIGURES_ERROR = 'FETCH_FIGURES_ERROR';

export const FETCH_SINGLE_FIGURE_REQUEST = 'FETCH_SINGLE_FIGURE_REQUEST';
export const FETCH_SINGLE_FIGURE_SUCCESS = 'FETCH_SINGLE_FIGURE_SUCCESS';
export const FETCH_SINGLE_FIGURE_ERROR = 'FETCH_SINGLE_FIGURE_ERROR';

export const ADD_TO_BOX = 'ADD_TO_BOX';
export const DELETE_FROM_BOX = 'DELETE_FROM_BOX';
